-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '{background}',
  base01 = '{color1}',
  base02 = '{color2}',
  base03 = '{color3}',
  base04 = '{color4}',
  base05 = '{color5}',
  base06 = '{color6}',
  base07 = '{color7}',

  base08 = '{color8}',
  base09 = '{color9}',
  base0A = '{color10}',
  base0B = '{color11}',
  base0C = '{color12}',
  base0D = '{color13}',
  base0E = '{color14}',
  base0F = '{color15}',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{color1}',
  fg = '{background}',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{color7}',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{color6}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{color7}',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{color2}',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{background}',
  fg = '{color7}',
})
