[color]
background = 'default'
foreground = '#8dd5b3'

; gradient = 0
gradient = 1
gradient_color_1 = '#005139'
gradient_color_2 = '#8dd5b3'
gradient_color_3 = '#a8f2ce'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#005139'
horizontal_gradient_color_2 = '#8dd5b3'
horizontal_gradient_color_3 = '#a8f2ce'
horizontal_gradient_color_4 = '#8dd5b3'
horizontal_gradient_color_5 = '#005139'


